export const jobs = [
  'chimney sweep',
  'fashion model',
  'actor/actress',
  'astronaut',
  'author/ess',
  'baker',
  'barber',
  'beautician',
  'biologist',
  'bricklayer, brickie',
  'bus driver',
  'butcher',
  'caretaker',
  'carpenter',
  'chef',
  'chemist',
  'childcare assistant',
  'coach',
  'construction worker',
  'cook',
  'cosmetician',
  'customer adviser',
  'dentist',
  'doctor',
  'electrician',
  'engineer',
  'explorer',
  'farmer',
  'fashion designer',
  'firefighter',
  'fitness instructor',
  'florist',
  'gardener',
  'glazier',
  'graphic artist/designer',
  'hairdresser hairstylist',
  'hunter/huntsman',
  'journalist',
  'make-up artist',
  'mechanic',
  'miner',
  'nurse',
  'nursery-school teacher',
  'painter',
  'paramedic',
  'physiotherapist',
  'pilot',
  'plumber',
  'police officer',
  'research scientist',
  'roofer',
  'secretary',
  'shepherd/ess',
  'shop assistant',
  'singer',
  'slater',
  'social worker',
  'surgeon',
  'taxi/cab driver',
  'teacher',
  'thatcher',
  'tiler',
  'tour guide',
  'truck driver',
  'undertaker',
  'vet',
  'vocalist',
  'waiter/waitress',
  'zoologist',
];
